import fs from "node:fs/promises";

import { loadConfig, type AppConfig } from "../config/env.js";
import { detectAutoMergeIntent } from "../intent/detect-auto-merge.js";
import { sendEmailNotificationHook } from "../notifications/email.js";
import { assertAllowedContentPaths, assertAllowedMutations } from "../policy/allowed-paths.js";
import { assertTargetContract, inspectTargetContract } from "../policy/target-contract.js";
import { generateAiMutationProposal } from "../ai/provider.js";
import {
  createGitHubClient,
  createOrUpdatePullRequest,
  enablePullRequestAutoMerge,
  parseRepoFullName,
  postPullRequestComment,
} from "../github/client.js";
import {
  checkoutAutomationBranch,
  commitAndPushChanges,
  getStagedPaths,
  getWorkingTreeChangedPaths,
  loadCurrentContentFiles,
  stageAllowedPaths,
  writeContentMutations,
} from "../github/working-copy.js";
import { parseRepositoryDispatch } from "../gmail-dispatch/parse-dispatch.js";
import type { NormalizedDispatchRequest } from "../types.js";

interface RunDispatchOptions {
  config?: AppConfig;
  eventPayload?: unknown;
}

function slugify(value: string): string {
  const slug = value
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");
  return slug || "content-update";
}

function buildBranchName(request: NormalizedDispatchRequest): string {
  const subjectSlug = slugify(request.subject).slice(0, 40);
  const requestSlug = slugify(request.requestId).slice(0, 20);
  return `portfolio-agent/${subjectSlug}-${requestSlug}`;
}

function buildCommitMessage(request: NormalizedDispatchRequest): string {
  const subject = request.subject.trim() || "portfolio content update";
  return `Update portfolio content: ${subject}`;
}

function buildPullRequestTitle(request: NormalizedDispatchRequest): string {
  return `Portfolio content update: ${request.subject || request.requestId}`;
}

function buildPullRequestBody(params: {
  branchName: string;
  changedPaths: readonly string[];
  proposalSummary: string;
  request: NormalizedDispatchRequest;
  shouldAutoMerge: boolean;
}) {
  const requestedPaths =
    params.request.requestedPaths.length > 0
      ? params.request.requestedPaths.map((pathname) => `- \`${pathname}\``).join("\n")
      : "- No explicit path subset requested";

  return [
    "## Portfolio update request",
    `- Request ID: \`${params.request.requestId}\``,
    `- Sender: ${params.request.sender.email}`,
    `- Subject: ${params.request.subject || "(no subject)"}`,
    `- Source label(s): ${params.request.labels.join(", ")}`,
    `- Auto-merge requested: ${params.shouldAutoMerge ? "yes" : "no"}`,
    "",
    "## Changed files",
    ...params.changedPaths.map((pathname) => `- \`${pathname}\``),
    "",
    "## Requested path scope",
    requestedPaths,
    "",
    "## AI summary",
    params.proposalSummary,
    "",
    "## Original email body",
    "```text",
    params.request.body,
    "```",
    "",
    `Generated by branch \`${params.branchName}\`.`,
  ].join("\n");
}

function ensureRequestedPathSubset(
  changedPaths: readonly string[],
  request: NormalizedDispatchRequest,
) {
  if (request.requestedPaths.length === 0) {
    return;
  }

  const requestedPathSet = new Set(request.requestedPaths);
  const unexpectedPaths = changedPaths.filter(
    (pathname) => !requestedPathSet.has(pathname as (typeof request.requestedPaths)[number]),
  );

  if (unexpectedPaths.length > 0) {
    throw new Error(
      `Run would modify paths outside the requested payload scope: ${unexpectedPaths.join(", ")}.`,
    );
  }
}

async function readEventPayload(config: AppConfig, inlinePayload?: unknown): Promise<unknown> {
  if (inlinePayload) {
    return inlinePayload;
  }

  if (!config.eventPath) {
    throw new Error("GITHUB_EVENT_PATH is required when no inline event payload is provided.");
  }

  const rawPayload = await fs.readFile(config.eventPath, "utf8");
  return JSON.parse(rawPayload) as unknown;
}

export async function runPortfolioDispatch(
  options: RunDispatchOptions = {},
) {
  const config = options.config ?? loadConfig();
  const eventPayload = await readEventPayload(config, options.eventPayload);
  const request = parseRepositoryDispatch(eventPayload, {
    defaultTargetRepo: config.targetRepo,
  });

  if (request.targetRepo !== config.targetRepo) {
    throw new Error(
      `Dispatch targeted ${request.targetRepo}, but this workflow is configured for ${config.targetRepo}.`,
    );
  }

  const targetContract = await inspectTargetContract(config.targetRepoPath);
  assertTargetContract(targetContract);

  const autoMergeIntent = detectAutoMergeIntent(request.body);
  const currentFiles = await loadCurrentContentFiles(config.targetRepoPath);
  const proposal = await generateAiMutationProposal({
    autoMergeIntent,
    config,
    currentFiles,
    request,
  });

  if (proposal.mutations.length === 0) {
    throw new Error("AI proposal did not include any content mutations.");
  }

  assertAllowedMutations(proposal.mutations, "AI proposal");
  ensureRequestedPathSubset(
    proposal.mutations.map((mutation) => mutation.path),
    request,
  );

  const branchName = buildBranchName(request);
  await checkoutAutomationBranch(config.targetRepoPath, branchName);
  await writeContentMutations(config.targetRepoPath, proposal.mutations);

  const changedPaths = await getWorkingTreeChangedPaths(config.targetRepoPath);
  if (changedPaths.length === 0) {
    throw new Error("The workflow produced no content changes after applying the AI proposal.");
  }

  assertAllowedContentPaths(changedPaths, "Final working tree");
  ensureRequestedPathSubset(changedPaths, request);
  await stageAllowedPaths(config.targetRepoPath, changedPaths);

  const stagedPaths = await getStagedPaths(config.targetRepoPath);
  if (stagedPaths.length === 0) {
    throw new Error("No staged content changes were found for commit creation.");
  }

  if (config.dryRun) {
    return {
      autoMergeEnabled: false,
      branchName,
      changedPaths: stagedPaths,
      proposalSummary: proposal.summary,
      requestId: request.requestId,
    };
  }

  await commitAndPushChanges({
    branchName,
    commitMessage: buildCommitMessage(request),
    targetRepoPath: config.targetRepoPath,
  });

  const octokit = createGitHubClient(config.githubToken);
  const repoRef = parseRepoFullName(config.targetRepo);
  const pullRequest = await createOrUpdatePullRequest(octokit, {
    base: config.targetBaseBranch,
    body: buildPullRequestBody({
      branchName,
      changedPaths: stagedPaths,
      proposalSummary: proposal.summary,
      request,
      shouldAutoMerge: autoMergeIntent.enabled,
    }),
    head: branchName,
    repoRef,
    title: buildPullRequestTitle(request),
  });

  const notificationBody = [
    `Created PR #${pullRequest.number} for request \`${request.requestId}\`.`,
    `Changed files: ${stagedPaths.join(", ")}.`,
    autoMergeIntent.enabled
      ? "Explicit auto-merge intent detected. Auto-merge will be enabled once GitHub accepts the request."
      : "PR-first mode retained because no explicit auto-merge phrase was detected.",
  ].join(" ");

  await postPullRequestComment(
    octokit,
    repoRef,
    pullRequest.number,
    notificationBody,
  );
  await sendEmailNotificationHook(config.emailNotificationWebhookUrl, {
    body: notificationBody,
    title: `Portfolio update request ${request.requestId}`,
  });

  if (autoMergeIntent.enabled) {
    await enablePullRequestAutoMerge(octokit, pullRequest.nodeId);
  }

  return {
    autoMergeEnabled: autoMergeIntent.enabled,
    branchName,
    changedPaths: stagedPaths,
    proposalSummary: proposal.summary,
    pullRequest,
    requestId: request.requestId,
  };
}
